# Generated by Django 4.2.5 on 2023-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('celik', 'Çelik Kapı'), ('ado', 'Ado Kapı'), ('icoda', 'İç Oda Kapı')], max_length=50)),
                ('kategoriResim', models.FileField(upload_to='kategoripic/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
        ),
    ]
