# Generated by Django 4.2.5 on 2023-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='isim',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
