# Generated by Django 4.2.5 on 2023-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0002_kategori_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='isim_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='isim_tr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
