# Generated by Django 4.2.5 on 2023-09-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0003_kategori_isim_en_kategori_isim_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='backImage',
            field=models.FileField(blank=True, null=True, upload_to='backgroundkategori'),
        ),
    ]
