# Generated by Django 4.2.5 on 2023-09-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0004_kategori_backimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunKodu', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('urunResim', models.FileField(upload_to='urunpic/')),
                ('icDolgu', models.TextField(blank=True, max_length=1000, null=True)),
                ('icKasa', models.TextField(blank=True, max_length=1000, null=True)),
                ('icPervaz', models.TextField(blank=True, max_length=1000, null=True)),
                ('icBoya', models.TextField(blank=True, max_length=1000, null=True)),
                ('icKanat', models.TextField(blank=True, max_length=1000, null=True)),
                ('icSerenler', models.TextField(blank=True, max_length=1000, null=True)),
                ('adoKanat', models.TextField(blank=True, max_length=1000, null=True)),
                ('adoKasaPervaz', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik1', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik2', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik3', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik4', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik5', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik6', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik7', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik8', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik9', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik10', models.TextField(blank=True, max_length=1000, null=True)),
                ('celikicerik11', models.TextField(blank=True, max_length=1000, null=True)),
                ('urunKategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karincaapp.kategori')),
            ],
        ),
    ]
