# Generated by Django 4.2.5 on 2023-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0006_urun_adokanat_en_urun_adokanat_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunResim2',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResim3',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResim4',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResim5',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResim6',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
    ]
