# Generated by Django 4.2.5 on 2023-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0007_urun_urunresim2_urun_urunresim3_urun_urunresim4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunKodu_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunKodu_tr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
