# Generated by Django 4.2.5 on 2023-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0009_urun_icmasif'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='icMasif_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='icMasif_tr',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
