# Generated by Django 4.2.5 on 2023-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0010_urun_icmasif_en_urun_icmasif_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunResim7',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResim8',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResim9',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
    ]
