# Generated by Django 4.2.5 on 2023-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karincaapp', '0011_urun_urunresim7_urun_urunresim8_urun_urunresim9'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunResim10',
            field=models.FileField(blank=True, null=True, upload_to='urunpic/'),
        ),
    ]
